import Head from 'next/head'
import { Inter } from '@next/font/google'
import Banner from '../Components/Banner/Banner'
import Navbar from '../Components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Shakhawat Hossain</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='h-screen bg-cover ' style={{
        backgroundImage : 'url(https://images.unsplash.com/32/Mc8kW4x9Q3aRR3RkP5Im_IMG_4417.jpg?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)'
      }}>
        <Navbar></Navbar>
        <Banner></Banner>
      </section>
    </>
  )
}
